package modelo;

public class formulario {

    int IDESTUDIANTE;
    String TIPOIDENTIFICACIONESTUDIANTE;
    String NUMIDENTIFICACIONESTUDIANTE;
    String PRIMERAPELLIDOESTUDIANTE;
    String SEGUNDOAPELLIDOESTUDIANTE;
    String PRIMERNOMBREESTUDIANTE;
    String SEGUNDONOMBREESTUDIANTE;
    String FECHANACIMIENTOESTUDIANTE;
    String GENEROESTUDIANTE;
    String ESTADOCIVILESTUDIANTE;
    String ETNIAESTUDIANTE;
    String PUEBLOESTUDIANTE;
    String TIPOSANGREESTUDIANTE;
    String TIENEDISCAPACIDAD;
    String PORCENTAJEDISCAPACIDADESTUDIANTE;
    String NUMCARNETESTUDIANTE;
    String TIPODISCAPACIDAD;
    String PROVINCIANACIMIENTOESTUDIANTE;
    String CANTONNACIMIENTOESTUDIANTE;
    String PROVINCIARESIDENCIAESTUDIANTE;
    String CANTONRESIDENCIAESTUDIANTE;
    String CORREOESTUDIANTE;
    String NUMEROCELULARESTUDIANTE;
    String NIVELFORMACIONPADREDEESTUDIANTE;
    String NIVELFORMACIONMADREDEESTUDIANTE;
    String INGRESOTOTALHOGARESTUDIANTE;
    String NUMEROMIEMBROSHOGARESTUDIANTE;
    String TIPOCOLEGIOESTUDIANTE;
    String MODALIDADCARRERAESTUDIANTE;
    String JORNADACARRERAESTUDIANTE;
    String FECHAINICIOCARRERAESTUDIANTE;
    String FECHAMATRICULAESTUDIANTE;
    String TIPOMATRICULAESTUDIANTE;
    String NIVELACADEMICOESTUDIANTE;
    String SEMANASDURACIONPERIODOESTUDIANTE;
    String REPETIDOMATERIAESTUDIANTE;
    String CARRERAESTUDIANTE;
    String PARALELOESTUDIANTE;
    String PERDIDOGRATUIDADESTUDIANTE;
    String POSEEPENSIONESTUDIANTE;
    String ENCUENTRADEDICADOESTUDIANTE;
    String EMPLEAINGRESOSESTUDIANTE;
    String FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE;
    String REALIZADOPRACTICASESTUDIANTE;
    String HORASPRACTICAREALIZOESTUDIANTE;
    String TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE;
    String SECTORECONOMICOPRACTICASESTUDIANTE;
    String PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE;
    String ALCANCEPROYECTOVINCULACIONESTUDIANTE;
    String COMPONENTEESTUDIANTE;
    String REQUISITOSCOMPONENTEESTUDIANTE;

    public formulario(String TIPOIDENTIFICACIONESTUDIANTE, String NUMIDENTIFICACIONESTUDIANTE, String PRIMERAPELLIDOESTUDIANTE, String SEGUNDOAPELLIDOESTUDIANTE, String PRIMERNOMBREESTUDIANTE, String SEGUNDONOMBREESTUDIANTE, String FECHANACIMIENTOESTUDIANTE, String GENEROESTUDIANTE, String ESTADOCIVILESTUDIANTE, String ETNIAESTUDIANTE, String PUEBLOESTUDIANTE, String TIPOSANGREESTUDIANTE, String TIENEDISCAPACIDAD, String PORCENTAJEDISCAPACIDADESTUDIANTE, String NUMCARNETESTUDIANTE, String TIPODISCAPACIDAD, String PROVINCIANACIMIENTOESTUDIANTE, String CANTONNACIMIENTOESTUDIANTE, String PROVINCIARESIDENCIAESTUDIANTE, String CANTONRESIDENCIAESTUDIANTE, String CORREOESTUDIANTE, String NUMEROCELULARESTUDIANTE, String NIVELFORMACIONPADREDEESTUDIANTE, String NIVELFORMACIONMADREDEESTUDIANTE, String INGRESOTOTALHOGARESTUDIANTE, String NUMEROMIEMBROSHOGARESTUDIANTE, String TIPOCOLEGIOESTUDIANTE, String MODALIDADCARRERAESTUDIANTE, String JORNADACARRERAESTUDIANTE, String FECHAINICIOCARRERAESTUDIANTE, String FECHAMATRICULAESTUDIANTE, String TIPOMATRICULAESTUDIANTE, String NIVELACADEMICOESTUDIANTE, String SEMANASDURACIONPERIODOESTUDIANTE, String REPETIDOMATERIAESTUDIANTE, String CARRERAESTUDIANTE, String PARALELOESTUDIANTE, String PERDIDOGRATUIDADESTUDIANTE, String POSEEPENSIONESTUDIANTE, String ENCUENTRADEDICADOESTUDIANTE, String EMPLEAINGRESOSESTUDIANTE, String FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE, String REALIZADOPRACTICASESTUDIANTE, String HORASPRACTICAREALIZOESTUDIANTE, String TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE, String SECTORECONOMICOPRACTICASESTUDIANTE, String PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE, String ALCANCEPROYECTOVINCULACIONESTUDIANTE, String COMPONENTEESTUDIANTE, String REQUISITOSCOMPONENTEESTUDIANTE) {
        this.TIPOIDENTIFICACIONESTUDIANTE = TIPOIDENTIFICACIONESTUDIANTE;
        this.NUMIDENTIFICACIONESTUDIANTE = NUMIDENTIFICACIONESTUDIANTE;
        this.PRIMERAPELLIDOESTUDIANTE = PRIMERAPELLIDOESTUDIANTE;
        this.SEGUNDOAPELLIDOESTUDIANTE = SEGUNDOAPELLIDOESTUDIANTE;
        this.PRIMERNOMBREESTUDIANTE = PRIMERNOMBREESTUDIANTE;
        this.SEGUNDONOMBREESTUDIANTE = SEGUNDONOMBREESTUDIANTE;
        this.FECHANACIMIENTOESTUDIANTE = FECHANACIMIENTOESTUDIANTE;
        this.GENEROESTUDIANTE = GENEROESTUDIANTE;
        this.ESTADOCIVILESTUDIANTE = ESTADOCIVILESTUDIANTE;
        this.ETNIAESTUDIANTE = ETNIAESTUDIANTE;
        this.PUEBLOESTUDIANTE = PUEBLOESTUDIANTE;
        this.TIPOSANGREESTUDIANTE = TIPOSANGREESTUDIANTE;
        this.TIENEDISCAPACIDAD = TIENEDISCAPACIDAD;
        this.PORCENTAJEDISCAPACIDADESTUDIANTE = PORCENTAJEDISCAPACIDADESTUDIANTE;
        this.NUMCARNETESTUDIANTE = NUMCARNETESTUDIANTE;
        this.TIPODISCAPACIDAD = TIPODISCAPACIDAD;
        this.PROVINCIANACIMIENTOESTUDIANTE = PROVINCIANACIMIENTOESTUDIANTE;
        this.CANTONNACIMIENTOESTUDIANTE = CANTONNACIMIENTOESTUDIANTE;
        this.PROVINCIARESIDENCIAESTUDIANTE = PROVINCIARESIDENCIAESTUDIANTE;
        this.CANTONRESIDENCIAESTUDIANTE = CANTONRESIDENCIAESTUDIANTE;
        this.CORREOESTUDIANTE = CORREOESTUDIANTE;
        this.NUMEROCELULARESTUDIANTE = NUMEROCELULARESTUDIANTE;
        this.NIVELFORMACIONPADREDEESTUDIANTE = NIVELFORMACIONPADREDEESTUDIANTE;
        this.NIVELFORMACIONMADREDEESTUDIANTE = NIVELFORMACIONMADREDEESTUDIANTE;
        this.INGRESOTOTALHOGARESTUDIANTE = INGRESOTOTALHOGARESTUDIANTE;
        this.NUMEROMIEMBROSHOGARESTUDIANTE = NUMEROMIEMBROSHOGARESTUDIANTE;
        this.TIPOCOLEGIOESTUDIANTE = TIPOCOLEGIOESTUDIANTE;
        this.MODALIDADCARRERAESTUDIANTE = MODALIDADCARRERAESTUDIANTE;
        this.JORNADACARRERAESTUDIANTE = JORNADACARRERAESTUDIANTE;
        this.FECHAINICIOCARRERAESTUDIANTE = FECHAINICIOCARRERAESTUDIANTE;
        this.FECHAMATRICULAESTUDIANTE = FECHAMATRICULAESTUDIANTE;
        this.TIPOMATRICULAESTUDIANTE = TIPOMATRICULAESTUDIANTE;
        this.NIVELACADEMICOESTUDIANTE = NIVELACADEMICOESTUDIANTE;
        this.SEMANASDURACIONPERIODOESTUDIANTE = SEMANASDURACIONPERIODOESTUDIANTE;
        this.REPETIDOMATERIAESTUDIANTE = REPETIDOMATERIAESTUDIANTE;
        this.CARRERAESTUDIANTE = CARRERAESTUDIANTE;
        this.PARALELOESTUDIANTE = PARALELOESTUDIANTE;
        this.PERDIDOGRATUIDADESTUDIANTE = PERDIDOGRATUIDADESTUDIANTE;
        this.POSEEPENSIONESTUDIANTE = POSEEPENSIONESTUDIANTE;
        this.ENCUENTRADEDICADOESTUDIANTE = ENCUENTRADEDICADOESTUDIANTE;
        this.EMPLEAINGRESOSESTUDIANTE = EMPLEAINGRESOSESTUDIANTE;
        this.FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE = FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE;
        this.REALIZADOPRACTICASESTUDIANTE = REALIZADOPRACTICASESTUDIANTE;
        this.HORASPRACTICAREALIZOESTUDIANTE = HORASPRACTICAREALIZOESTUDIANTE;
        this.TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE = TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE;
        this.SECTORECONOMICOPRACTICASESTUDIANTE = SECTORECONOMICOPRACTICASESTUDIANTE;
        this.PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE = PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE;
        this.ALCANCEPROYECTOVINCULACIONESTUDIANTE = ALCANCEPROYECTOVINCULACIONESTUDIANTE;
        this.COMPONENTEESTUDIANTE = COMPONENTEESTUDIANTE;
        this.REQUISITOSCOMPONENTEESTUDIANTE = REQUISITOSCOMPONENTEESTUDIANTE;
    }

   

    public formulario(int IDESTUDIANTE, String TIPOIDENTIFICACIONESTUDIANTE, String NUMIDENTIFICACIONESTUDIANTE, String PRIMERAPELLIDOESTUDIANTE, String SEGUNDOAPELLIDOESTUDIANTE, String PRIMERNOMBREESTUDIANTE, String SEGUNDONOMBREESTUDIANTE, String FECHANACIMIENTOESTUDIANTE, String GENEROESTUDIANTE, String ESTADOCIVILESTUDIANTE, String ETNIAESTUDIANTE, String PUEBLOESTUDIANTE, String TIPOSANGREESTUDIANTE, String TIENEDISCAPACIDAD, String PORCENTAJEDISCAPACIDADESTUDIANTE, String NUMCARNETESTUDIANTE, String TIPODISCAPACIDAD, String PROVINCIANACIMIENTOESTUDIANTE, String CANTONNACIMIENTOESTUDIANTE, String PROVINCIARESIDENCIAESTUDIANTE, String CANTONRESIDENCIAESTUDIANTE, String CORREOESTUDIANTE, String NUMEROCELULARESTUDIANTE, String NIVELFORMACIONPADREDEESTUDIANTE, String NIVELFORMACIONMADREDEESTUDIANTE, String INGRESOTOTALHOGARESTUDIANTE, String NUMEROMIEMBROSHOGARESTUDIANTE, String TIPOCOLEGIOESTUDIANTE, String MODALIDADCARRERAESTUDIANTE, String JORNADACARRERAESTUDIANTE, String FECHAINICIOCARRERAESTUDIANTE, String FECHAMATRICULAESTUDIANTE, String TIPOMATRICULAESTUDIANTE, String NIVELACADEMICOESTUDIANTE, String SEMANASDURACIONPERIODOESTUDIANTE, String REPETIDOMATERIAESTUDIANTE, String CARRERAESTUDIANTE, String PARALELOESTUDIANTE, String PERDIDOGRATUIDADESTUDIANTE, String POSEEPENSIONESTUDIANTE, String ENCUENTRADEDICADOESTUDIANTE, String EMPLEAINGRESOSESTUDIANTE, String FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE, String REALIZADOPRACTICASESTUDIANTE, String HORASPRACTICAREALIZOESTUDIANTE, String TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE, String SECTORECONOMICOPRACTICASESTUDIANTE, String PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE, String ALCANCEPROYECTOVINCULACIONESTUDIANTE, String COMPONENTEESTUDIANTE, String REQUISITOSCOMPONENTEESTUDIANTE) {
        this.IDESTUDIANTE = IDESTUDIANTE;
        this.TIPOIDENTIFICACIONESTUDIANTE = TIPOIDENTIFICACIONESTUDIANTE;
        this.NUMIDENTIFICACIONESTUDIANTE = NUMIDENTIFICACIONESTUDIANTE;
        this.PRIMERAPELLIDOESTUDIANTE = PRIMERAPELLIDOESTUDIANTE;
        this.SEGUNDOAPELLIDOESTUDIANTE = SEGUNDOAPELLIDOESTUDIANTE;
        this.PRIMERNOMBREESTUDIANTE = PRIMERNOMBREESTUDIANTE;
        this.SEGUNDONOMBREESTUDIANTE = SEGUNDONOMBREESTUDIANTE;
        this.FECHANACIMIENTOESTUDIANTE = FECHANACIMIENTOESTUDIANTE;
        this.GENEROESTUDIANTE = GENEROESTUDIANTE;
        this.ESTADOCIVILESTUDIANTE = ESTADOCIVILESTUDIANTE;
        this.ETNIAESTUDIANTE = ETNIAESTUDIANTE;
        this.PUEBLOESTUDIANTE = PUEBLOESTUDIANTE;
        this.TIPOSANGREESTUDIANTE = TIPOSANGREESTUDIANTE;
        this.TIENEDISCAPACIDAD = TIENEDISCAPACIDAD;
        this.PORCENTAJEDISCAPACIDADESTUDIANTE = PORCENTAJEDISCAPACIDADESTUDIANTE;
        this.NUMCARNETESTUDIANTE = NUMCARNETESTUDIANTE;
        this.TIPODISCAPACIDAD = TIPODISCAPACIDAD;
        this.PROVINCIANACIMIENTOESTUDIANTE = PROVINCIANACIMIENTOESTUDIANTE;
        this.CANTONNACIMIENTOESTUDIANTE = CANTONNACIMIENTOESTUDIANTE;
        this.PROVINCIARESIDENCIAESTUDIANTE = PROVINCIARESIDENCIAESTUDIANTE;
        this.CANTONRESIDENCIAESTUDIANTE = CANTONRESIDENCIAESTUDIANTE;
        this.CORREOESTUDIANTE = CORREOESTUDIANTE;
        this.NUMEROCELULARESTUDIANTE = NUMEROCELULARESTUDIANTE;
        this.NIVELFORMACIONPADREDEESTUDIANTE = NIVELFORMACIONPADREDEESTUDIANTE;
        this.NIVELFORMACIONMADREDEESTUDIANTE = NIVELFORMACIONMADREDEESTUDIANTE;
        this.INGRESOTOTALHOGARESTUDIANTE = INGRESOTOTALHOGARESTUDIANTE;
        this.NUMEROMIEMBROSHOGARESTUDIANTE = NUMEROMIEMBROSHOGARESTUDIANTE;
        this.TIPOCOLEGIOESTUDIANTE = TIPOCOLEGIOESTUDIANTE;
        this.MODALIDADCARRERAESTUDIANTE = MODALIDADCARRERAESTUDIANTE;
        this.JORNADACARRERAESTUDIANTE = JORNADACARRERAESTUDIANTE;
        this.FECHAINICIOCARRERAESTUDIANTE = FECHAINICIOCARRERAESTUDIANTE;
        this.FECHAMATRICULAESTUDIANTE = FECHAMATRICULAESTUDIANTE;
        this.TIPOMATRICULAESTUDIANTE = TIPOMATRICULAESTUDIANTE;
        this.NIVELACADEMICOESTUDIANTE = NIVELACADEMICOESTUDIANTE;
        this.SEMANASDURACIONPERIODOESTUDIANTE = SEMANASDURACIONPERIODOESTUDIANTE;
        this.REPETIDOMATERIAESTUDIANTE = REPETIDOMATERIAESTUDIANTE;
        this.CARRERAESTUDIANTE = CARRERAESTUDIANTE;
        this.PARALELOESTUDIANTE = PARALELOESTUDIANTE;
        this.PERDIDOGRATUIDADESTUDIANTE = PERDIDOGRATUIDADESTUDIANTE;
        this.POSEEPENSIONESTUDIANTE = POSEEPENSIONESTUDIANTE;
        this.ENCUENTRADEDICADOESTUDIANTE = ENCUENTRADEDICADOESTUDIANTE;
        this.EMPLEAINGRESOSESTUDIANTE = EMPLEAINGRESOSESTUDIANTE;
        this.FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE = FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE;
        this.REALIZADOPRACTICASESTUDIANTE = REALIZADOPRACTICASESTUDIANTE;
        this.HORASPRACTICAREALIZOESTUDIANTE = HORASPRACTICAREALIZOESTUDIANTE;
        this.TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE = TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE;
        this.SECTORECONOMICOPRACTICASESTUDIANTE = SECTORECONOMICOPRACTICASESTUDIANTE;
        this.PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE = PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE;
        this.ALCANCEPROYECTOVINCULACIONESTUDIANTE = ALCANCEPROYECTOVINCULACIONESTUDIANTE;
        this.COMPONENTEESTUDIANTE = COMPONENTEESTUDIANTE;
        this.REQUISITOSCOMPONENTEESTUDIANTE = REQUISITOSCOMPONENTEESTUDIANTE;
    }

    public formulario() {
        
    }

    public int getIDESTUDIANTE() {
        return IDESTUDIANTE;
    }

    public void setIDESTUDIANTE(int IDESTUDIANTE) {
        this.IDESTUDIANTE = IDESTUDIANTE;
    }

    public String getTIPOIDENTIFICACIONESTUDIANTE() {
        return TIPOIDENTIFICACIONESTUDIANTE;
    }

    public void setTIPOIDENTIFICACIONESTUDIANTE(String TIPOIDENTIFICACIONESTUDIANTE) {
        this.TIPOIDENTIFICACIONESTUDIANTE = TIPOIDENTIFICACIONESTUDIANTE;
    }

    public String getNUMIDENTIFICACIONESTUDIANTE() {
        return NUMIDENTIFICACIONESTUDIANTE;
    }

    public void setNUMIDENTIFICACIONESTUDIANTE(String NUMIDENTIFICACIONESTUDIANTE) {
        this.NUMIDENTIFICACIONESTUDIANTE = NUMIDENTIFICACIONESTUDIANTE;
    }

    public String getPRIMERAPELLIDOESTUDIANTE() {
        return PRIMERAPELLIDOESTUDIANTE;
    }

    public void setPRIMERAPELLIDOESTUDIANTE(String PRIMERAPELLIDOESTUDIANTE) {
        this.PRIMERAPELLIDOESTUDIANTE = PRIMERAPELLIDOESTUDIANTE;
    }

    public String getSEGUNDOAPELLIDOESTUDIANTE() {
        return SEGUNDOAPELLIDOESTUDIANTE;
    }

    public void setSEGUNDOAPELLIDOESTUDIANTE(String SEGUNDOAPELLIDOESTUDIANTE) {
        this.SEGUNDOAPELLIDOESTUDIANTE = SEGUNDOAPELLIDOESTUDIANTE;
    }

    public String getPRIMERNOMBREESTUDIANTE() {
        return PRIMERNOMBREESTUDIANTE;
    }

    public void setPRIMERNOMBREESTUDIANTE(String PRIMERNOMBREESTUDIANTE) {
        this.PRIMERNOMBREESTUDIANTE = PRIMERNOMBREESTUDIANTE;
    }

    public String getSEGUNDONOMBREESTUDIANTE() {
        return SEGUNDONOMBREESTUDIANTE;
    }

    public void setSEGUNDONOMBREESTUDIANTE(String SEGUNDONOMBREESTUDIANTE) {
        this.SEGUNDONOMBREESTUDIANTE = SEGUNDONOMBREESTUDIANTE;
    }

    public String getFECHANACIMIENTOESTUDIANTE() {
        return FECHANACIMIENTOESTUDIANTE;
    }

    public void setFECHANACIMIENTOESTUDIANTE(String FECHANACIMIENTOESTUDIANTE) {
        this.FECHANACIMIENTOESTUDIANTE = FECHANACIMIENTOESTUDIANTE;
    }

    public String getGENEROESTUDIANTE() {
        return GENEROESTUDIANTE;
    }

    public void setGENEROESTUDIANTE(String GENEROESTUDIANTE) {
        this.GENEROESTUDIANTE = GENEROESTUDIANTE;
    }

    public String getESTADOCIVILESTUDIANTE() {
        return ESTADOCIVILESTUDIANTE;
    }

    public void setESTADOCIVILESTUDIANTE(String ESTADOCIVILESTUDIANTE) {
        this.ESTADOCIVILESTUDIANTE = ESTADOCIVILESTUDIANTE;
    }

    public String getETNIAESTUDIANTE() {
        return ETNIAESTUDIANTE;
    }

    public void setETNIAESTUDIANTE(String ETNIAESTUDIANTE) {
        this.ETNIAESTUDIANTE = ETNIAESTUDIANTE;
    }

    public String getPUEBLOESTUDIANTE() {
        return PUEBLOESTUDIANTE;
    }

    public void setPUEBLOESTUDIANTE(String PUEBLOESTUDIANTE) {
        this.PUEBLOESTUDIANTE = PUEBLOESTUDIANTE;
    }

    public String getTIPOSANGREESTUDIANTE() {
        return TIPOSANGREESTUDIANTE;
    }

    public void setTIPOSANGREESTUDIANTE(String TIPOSANGREESTUDIANTE) {
        this.TIPOSANGREESTUDIANTE = TIPOSANGREESTUDIANTE;
    }

    public String getTIENEDISCAPACIDAD() {
        return TIENEDISCAPACIDAD;
    }

    public void setTIENEDISCAPACIDAD(String TIENEDISCAPACIDAD) {
        this.TIENEDISCAPACIDAD = TIENEDISCAPACIDAD;
    }

    public String getPORCENTAJEDISCAPACIDADESTUDIANTE() {
        return PORCENTAJEDISCAPACIDADESTUDIANTE;
    }

    public void setPORCENTAJEDISCAPACIDADESTUDIANTE(String PORCENTAJEDISCAPACIDADESTUDIANTE) {
        this.PORCENTAJEDISCAPACIDADESTUDIANTE = PORCENTAJEDISCAPACIDADESTUDIANTE;
    }

    public String getNUMCARNETESTUDIANTE() {
        return NUMCARNETESTUDIANTE;
    }

    public void setNUMCARNETESTUDIANTE(String NUMCARNETESTUDIANTE) {
        this.NUMCARNETESTUDIANTE = NUMCARNETESTUDIANTE;
    }

    public String getTIPODISCAPACIDAD() {
        return TIPODISCAPACIDAD;
    }

    public void setTIPODISCAPACIDAD(String TIPODISCAPACIDAD) {
        this.TIPODISCAPACIDAD = TIPODISCAPACIDAD;
    }

    public String getPROVINCIANACIMIENTOESTUDIANTE() {
        return PROVINCIANACIMIENTOESTUDIANTE;
    }

    public void setPROVINCIANACIMIENTOESTUDIANTE(String PROVINCIANACIMIENTOESTUDIANTE) {
        this.PROVINCIANACIMIENTOESTUDIANTE = PROVINCIANACIMIENTOESTUDIANTE;
    }

    public String getCANTONNACIMIENTOESTUDIANTE() {
        return CANTONNACIMIENTOESTUDIANTE;
    }

    public void setCANTONNACIMIENTOESTUDIANTE(String CANTONNACIMIENTOESTUDIANTE) {
        this.CANTONNACIMIENTOESTUDIANTE = CANTONNACIMIENTOESTUDIANTE;
    }

    public String getPROVINCIARESIDENCIAESTUDIANTE() {
        return PROVINCIARESIDENCIAESTUDIANTE;
    }

    public void setPROVINCIARESIDENCIAESTUDIANTE(String PROVINCIARESIDENCIAESTUDIANTE) {
        this.PROVINCIARESIDENCIAESTUDIANTE = PROVINCIARESIDENCIAESTUDIANTE;
    }

    public String getCANTONRESIDENCIAESTUDIANTE() {
        return CANTONRESIDENCIAESTUDIANTE;
    }

    public void setCANTONRESIDENCIAESTUDIANTE(String CANTONRESIDENCIAESTUDIANTE) {
        this.CANTONRESIDENCIAESTUDIANTE = CANTONRESIDENCIAESTUDIANTE;
    }

    public String getCORREOESTUDIANTE() {
        return CORREOESTUDIANTE;
    }

    public void setCORREOESTUDIANTE(String CORREOESTUDIANTE) {
        this.CORREOESTUDIANTE = CORREOESTUDIANTE;
    }

    public String getNUMEROCELULARESTUDIANTE() {
        return NUMEROCELULARESTUDIANTE;
    }

    public void setNUMEROCELULARESTUDIANTE(String NUMEROCELULARESTUDIANTE) {
        this.NUMEROCELULARESTUDIANTE = NUMEROCELULARESTUDIANTE;
    }

    public String getNIVELFORMACIONPADREDEESTUDIANTE() {
        return NIVELFORMACIONPADREDEESTUDIANTE;
    }

    public void setNIVELFORMACIONPADREDEESTUDIANTE(String NIVELFORMACIONPADREDEESTUDIANTE) {
        this.NIVELFORMACIONPADREDEESTUDIANTE = NIVELFORMACIONPADREDEESTUDIANTE;
    }

    public String getNIVELFORMACIONMADREDEESTUDIANTE() {
        return NIVELFORMACIONMADREDEESTUDIANTE;
    }

    public void setNIVELFORMACIONMADREDEESTUDIANTE(String NIVELFORMACIONMADREDEESTUDIANTE) {
        this.NIVELFORMACIONMADREDEESTUDIANTE = NIVELFORMACIONMADREDEESTUDIANTE;
    }

    public String getINGRESOTOTALHOGARESTUDIANTE() {
        return INGRESOTOTALHOGARESTUDIANTE;
    }

    public void setINGRESOTOTALHOGARESTUDIANTE(String INGRESOTOTALHOGARESTUDIANTE) {
        this.INGRESOTOTALHOGARESTUDIANTE = INGRESOTOTALHOGARESTUDIANTE;
    }

    public String getNUMEROMIEMBROSHOGARESTUDIANTE() {
        return NUMEROMIEMBROSHOGARESTUDIANTE;
    }

    public void setNUMEROMIEMBROSHOGARESTUDIANTE(String NUMEROMIEMBROSHOGARESTUDIANTE) {
        this.NUMEROMIEMBROSHOGARESTUDIANTE = NUMEROMIEMBROSHOGARESTUDIANTE;
    }

    public String getTIPOCOLEGIOESTUDIANTE() {
        return TIPOCOLEGIOESTUDIANTE;
    }

    public void setTIPOCOLEGIOESTUDIANTE(String TIPOCOLEGIOESTUDIANTE) {
        this.TIPOCOLEGIOESTUDIANTE = TIPOCOLEGIOESTUDIANTE;
    }

    public String getMODALIDADCARRERAESTUDIANTE() {
        return MODALIDADCARRERAESTUDIANTE;
    }

    public void setMODALIDADCARRERAESTUDIANTE(String MODALIDADCARRERAESTUDIANTE) {
        this.MODALIDADCARRERAESTUDIANTE = MODALIDADCARRERAESTUDIANTE;
    }

    public String getJORNADACARRERAESTUDIANTE() {
        return JORNADACARRERAESTUDIANTE;
    }

    public void setJORNADACARRERAESTUDIANTE(String JORNADACARRERAESTUDIANTE) {
        this.JORNADACARRERAESTUDIANTE = JORNADACARRERAESTUDIANTE;
    }

    public String getFECHAINICIOCARRERAESTUDIANTE() {
        return FECHAINICIOCARRERAESTUDIANTE;
    }

    public void setFECHAINICIOCARRERAESTUDIANTE(String FECHAINICIOCARRERAESTUDIANTE) {
        this.FECHAINICIOCARRERAESTUDIANTE = FECHAINICIOCARRERAESTUDIANTE;
    }

    public String getFECHAMATRICULAESTUDIANTE() {
        return FECHAMATRICULAESTUDIANTE;
    }

    public void setFECHAMATRICULAESTUDIANTE(String FECHAMATRICULAESTUDIANTE) {
        this.FECHAMATRICULAESTUDIANTE = FECHAMATRICULAESTUDIANTE;
    }

    public String getTIPOMATRICULAESTUDIANTE() {
        return TIPOMATRICULAESTUDIANTE;
    }

    public void setTIPOMATRICULAESTUDIANTE(String TIPOMATRICULAESTUDIANTE) {
        this.TIPOMATRICULAESTUDIANTE = TIPOMATRICULAESTUDIANTE;
    }

    public String getNIVELACADEMICOESTUDIANTE() {
        return NIVELACADEMICOESTUDIANTE;
    }

    public void setNIVELACADEMICOESTUDIANTE(String NIVELACADEMICOESTUDIANTE) {
        this.NIVELACADEMICOESTUDIANTE = NIVELACADEMICOESTUDIANTE;
    }

    public String getSEMANASDURACIONPERIODOESTUDIANTE() {
        return SEMANASDURACIONPERIODOESTUDIANTE;
    }

    public void setSEMANASDURACIONPERIODOESTUDIANTE(String SEMANASDURACIONPERIODOESTUDIANTE) {
        this.SEMANASDURACIONPERIODOESTUDIANTE = SEMANASDURACIONPERIODOESTUDIANTE;
    }

    public String getREPETIDOMATERIAESTUDIANTE() {
        return REPETIDOMATERIAESTUDIANTE;
    }

    public void setREPETIDOMATERIAESTUDIANTE(String REPETIDOMATERIAESTUDIANTE) {
        this.REPETIDOMATERIAESTUDIANTE = REPETIDOMATERIAESTUDIANTE;
    }

    public String getCARRERAESTUDIANTE() {
        return CARRERAESTUDIANTE;
    }

    public void setCARRERAESTUDIANTE(String CARRERAESTUDIANTE) {
        this.CARRERAESTUDIANTE = CARRERAESTUDIANTE;
    }

    public String getPARALELOESTUDIANTE() {
        return PARALELOESTUDIANTE;
    }

    public void setPARALELOESTUDIANTE(String PARALELOESTUDIANTE) {
        this.PARALELOESTUDIANTE = PARALELOESTUDIANTE;
    }

    public String getPERDIDOGRATUIDADESTUDIANTE() {
        return PERDIDOGRATUIDADESTUDIANTE;
    }

    public void setPERDIDOGRATUIDADESTUDIANTE(String PERDIDOGRATUIDADESTUDIANTE) {
        this.PERDIDOGRATUIDADESTUDIANTE = PERDIDOGRATUIDADESTUDIANTE;
    }

    public String getPOSEEPENSIONESTUDIANTE() {
        return POSEEPENSIONESTUDIANTE;
    }

    public void setPOSEEPENSIONESTUDIANTE(String POSEEPENSIONESTUDIANTE) {
        this.POSEEPENSIONESTUDIANTE = POSEEPENSIONESTUDIANTE;
    }

    public String getENCUENTRADEDICADOESTUDIANTE() {
        return ENCUENTRADEDICADOESTUDIANTE;
    }

    public void setENCUENTRADEDICADOESTUDIANTE(String ENCUENTRADEDICADOESTUDIANTE) {
        this.ENCUENTRADEDICADOESTUDIANTE = ENCUENTRADEDICADOESTUDIANTE;
    }

    public String getEMPLEAINGRESOSESTUDIANTE() {
        return EMPLEAINGRESOSESTUDIANTE;
    }

    public void setEMPLEAINGRESOSESTUDIANTE(String EMPLEAINGRESOSESTUDIANTE) {
        this.EMPLEAINGRESOSESTUDIANTE = EMPLEAINGRESOSESTUDIANTE;
    }

    public String getFAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE() {
        return FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE;
    }

    public void setFAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE(String FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE) {
        this.FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE = FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE;
    }

    public String getREALIZADOPRACTICASESTUDIANTE() {
        return REALIZADOPRACTICASESTUDIANTE;
    }

    public void setREALIZADOPRACTICASESTUDIANTE(String REALIZADOPRACTICASESTUDIANTE) {
        this.REALIZADOPRACTICASESTUDIANTE = REALIZADOPRACTICASESTUDIANTE;
    }

    public String getHORASPRACTICAREALIZOESTUDIANTE() {
        return HORASPRACTICAREALIZOESTUDIANTE;
    }

    public void setHORASPRACTICAREALIZOESTUDIANTE(String HORASPRACTICAREALIZOESTUDIANTE) {
        this.HORASPRACTICAREALIZOESTUDIANTE = HORASPRACTICAREALIZOESTUDIANTE;
    }

    public String getTIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE() {
        return TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE;
    }

    public void setTIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE(String TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE) {
        this.TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE = TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE;
    }

    public String getSECTORECONOMICOPRACTICASESTUDIANTE() {
        return SECTORECONOMICOPRACTICASESTUDIANTE;
    }

    public void setSECTORECONOMICOPRACTICASESTUDIANTE(String SECTORECONOMICOPRACTICASESTUDIANTE) {
        this.SECTORECONOMICOPRACTICASESTUDIANTE = SECTORECONOMICOPRACTICASESTUDIANTE;
    }

    public String getPARTICIPADOPROYECTODEVINCULACIONESTUDIANTE() {
        return PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE;
    }

    public void setPARTICIPADOPROYECTODEVINCULACIONESTUDIANTE(String PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE) {
        this.PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE = PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE;
    }

    public String getALCANCEPROYECTOVINCULACIONESTUDIANTE() {
        return ALCANCEPROYECTOVINCULACIONESTUDIANTE;
    }

    public void setALCANCEPROYECTOVINCULACIONESTUDIANTE(String ALCANCEPROYECTOVINCULACIONESTUDIANTE) {
        this.ALCANCEPROYECTOVINCULACIONESTUDIANTE = ALCANCEPROYECTOVINCULACIONESTUDIANTE;
    }

    public String getCOMPONENTEESTUDIANTE() {
        return COMPONENTEESTUDIANTE;
    }

    public void setCOMPONENTEESTUDIANTE(String COMPONENTEESTUDIANTE) {
        this.COMPONENTEESTUDIANTE = COMPONENTEESTUDIANTE;
    }

    public String getREQUISITOSCOMPONENTEESTUDIANTE() {
        return REQUISITOSCOMPONENTEESTUDIANTE;
    }

    public void setREQUISITOSCOMPONENTEESTUDIANTE(String REQUISITOSCOMPONENTEESTUDIANTE) {
        this.REQUISITOSCOMPONENTEESTUDIANTE = REQUISITOSCOMPONENTEESTUDIANTE;
    }

    @Override
    public String toString() {
        return "formulario{" + "IDESTUDIANTE=" + IDESTUDIANTE + ", TIPOIDENTIFICACIONESTUDIANTE=" + TIPOIDENTIFICACIONESTUDIANTE + ", NUMIDENTIFICACIONESTUDIANTE=" + NUMIDENTIFICACIONESTUDIANTE + ", PRIMERAPELLIDOESTUDIANTE=" + PRIMERAPELLIDOESTUDIANTE + ", SEGUNDOAPELLIDOESTUDIANTE=" + SEGUNDOAPELLIDOESTUDIANTE + ", PRIMERNOMBREESTUDIANTE=" + PRIMERNOMBREESTUDIANTE + ", SEGUNDONOMBREESTUDIANTE=" + SEGUNDONOMBREESTUDIANTE + ", FECHANACIMIENTOESTUDIANTE=" + FECHANACIMIENTOESTUDIANTE + ", GENEROESTUDIANTE=" + GENEROESTUDIANTE + ", ESTADOCIVILESTUDIANTE=" + ESTADOCIVILESTUDIANTE + ", ETNIAESTUDIANTE=" + ETNIAESTUDIANTE + ", PUEBLOESTUDIANTE=" + PUEBLOESTUDIANTE + ", TIPOSANGREESTUDIANTE=" + TIPOSANGREESTUDIANTE + ", TIENEDISCAPACIDAD=" + TIENEDISCAPACIDAD + ", PORCENTAJEDISCAPACIDADESTUDIANTE=" + PORCENTAJEDISCAPACIDADESTUDIANTE + ", NUMCARNETESTUDIANTE=" + NUMCARNETESTUDIANTE + ", TIPODISCAPACIDAD=" + TIPODISCAPACIDAD + ", PROVINCIANACIMIENTOESTUDIANTE=" + PROVINCIANACIMIENTOESTUDIANTE + ", CANTONNACIMIENTOESTUDIANTE=" + CANTONNACIMIENTOESTUDIANTE + ", PROVINCIARESIDENCIAESTUDIANTE=" + PROVINCIARESIDENCIAESTUDIANTE + ", CANTONRESIDENCIAESTUDIANTE=" + CANTONRESIDENCIAESTUDIANTE + ", CORREOESTUDIANTE=" + CORREOESTUDIANTE + ", NUMEROCELULARESTUDIANTE=" + NUMEROCELULARESTUDIANTE + ", NIVELFORMACIONPADREDEESTUDIANTE=" + NIVELFORMACIONPADREDEESTUDIANTE + ", NIVELFORMACIONMADREDEESTUDIANTE=" + NIVELFORMACIONMADREDEESTUDIANTE + ", INGRESOTOTALHOGARESTUDIANTE=" + INGRESOTOTALHOGARESTUDIANTE + ", NUMEROMIEMBROSHOGARESTUDIANTE=" + NUMEROMIEMBROSHOGARESTUDIANTE + ", TIPOCOLEGIOESTUDIANTE=" + TIPOCOLEGIOESTUDIANTE + ", MODALIDADCARRERAESTUDIANTE=" + MODALIDADCARRERAESTUDIANTE + ", JORNADACARRERAESTUDIANTE=" + JORNADACARRERAESTUDIANTE + ", FECHAINICIOCARRERAESTUDIANTE=" + FECHAINICIOCARRERAESTUDIANTE + ", FECHAMATRICULAESTUDIANTE=" + FECHAMATRICULAESTUDIANTE + ", TIPOMATRICULAESTUDIANTE=" + TIPOMATRICULAESTUDIANTE + ", NIVELACADEMICOESTUDIANTE=" + NIVELACADEMICOESTUDIANTE + ", SEMANASDURACIONPERIODOESTUDIANTE=" + SEMANASDURACIONPERIODOESTUDIANTE + ", REPETIDOMATERIAESTUDIANTE=" + REPETIDOMATERIAESTUDIANTE + ", CARRERAESTUDIANTE=" + CARRERAESTUDIANTE + ", PARALELOESTUDIANTE=" + PARALELOESTUDIANTE + ", PERDIDOGRATUIDADESTUDIANTE=" + PERDIDOGRATUIDADESTUDIANTE + ", POSEEPENSIONESTUDIANTE=" + POSEEPENSIONESTUDIANTE + ", ENCUENTRADEDICADOESTUDIANTE=" + ENCUENTRADEDICADOESTUDIANTE + ", EMPLEAINGRESOSESTUDIANTE=" + EMPLEAINGRESOSESTUDIANTE + ", FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE=" + FAMILIARECIBEBONODESARROLLOHUMANOESTUDIANTE + ", REALIZADOPRACTICASESTUDIANTE=" + REALIZADOPRACTICASESTUDIANTE + ", HORASPRACTICAREALIZOESTUDIANTE=" + HORASPRACTICAREALIZOESTUDIANTE + ", TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE=" + TIPOINSTITUCIONREALIZAPRACTICASESTUDIANTE + ", SECTORECONOMICOPRACTICASESTUDIANTE=" + SECTORECONOMICOPRACTICASESTUDIANTE + ", PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE=" + PARTICIPADOPROYECTODEVINCULACIONESTUDIANTE + ", ALCANCEPROYECTOVINCULACIONESTUDIANTE=" + ALCANCEPROYECTOVINCULACIONESTUDIANTE + ", COMPONENTEESTUDIANTE=" + COMPONENTEESTUDIANTE + ", REQUISITOSCOMPONENTEESTUDIANTE=" + REQUISITOSCOMPONENTEESTUDIANTE + '}';
    }
    
    

}
